export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_PRODUCTS_DETAILS_REQ = "GET_PRODUCTS_DETAILS_REQ";
export const GET_PRODUCTS_DETAILS_SUCCESS = "GET_PRODUCTS_DETAILS_SUCCESS"
export const GET_PRODUCTS_DETAILS_FAIL = "GET_PRODUCTS_DETAILS_FAIL"
export const GET_PRODUCTS_DETAILS_RESET = "GET_PRODUCTS_DETAILS_RESET"
